export const FETCH_TEIS = 'FETCH_TEIS'
export const RECEIVE_TEIS = 'RECEIVE_TEIS'
export const RECEIVE_TEI = 'RECEIVE_TEI'
export const FETCH_TEI = 'FETCH_TEI'
export const SEND_PRINTED = 'SEND_PRINTED'
export const SEND_PRINTED_OK = 'SEND_PRINTED_OK'