export const COVID_VACCINE_PROGRAM = 'c9m3ufPy8D6'

export const CODE = 'A1bNxMuvb66'
export const NOM = 'bbOBxG4F6ja'
export const PRENOM = 'bXEwbxbLR9a'
export const TELEPHONE = 'cWAOfDiaXRJ'
export const QUARTIER = 'wlud1vswX9j'
export const REGION = 'WAvcn9eW1IH'
export const DISTRICT = 'rkQEv1WFZ1u'
export const SOUS_PREFECTURE = 'xCc7On3MR53'
export const SEXE = 'Mj4c07bIa9v'
export const DATE_NAISSANCE = 'X2ewZ9nk3r0'
export const PROFESSION = 'oM60JxeliEy'
export const AUTRE_PROFESSION = 'NbzrdyiCgYF'

export const LOT = 'LqjoygdutkZ'
export const TYPE_VACCIN = 'Rwaod1ZtWqW'
export const SITE = 'ajd9AeY7yJ7'
export const DATE_VACCINATION = 'kd5c8OH1vYM'
